CREATE TABLE Registrated_User(
  USER_ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR(20),
  U_PASSWORD VARCHAR(15),
  FULL_NAME VARCHAR(50),
  GENDER VARCHAR(1),
  DOB DATE,
  EMAIL VARCHAR(50), 
  U_ADDRESS VARCHAR(200),
  CONTACT VARCHAR(20),
  U_ROLE VARCHAR(10),
  REG_DATE_TIME TIMESTAMP
); 