FROM arm64v8/openjdk:17
LABEL maintainer="himhim479@gmail.com"
ADD target/demo-openrice-0.0.1-SNAPSHOT.jar demo-openrice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-openrice-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080