FROM arm64v8/openjdk:17
LABEL maintainer="himhim479@gmail.com"
ADD target/basic-user-management-0.0.1-SNAPSHOT.jar basic-user-management-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java" , "-jar" , "basic-user-management-0.0.1-SNAPSHOT.jar" ]
EXPOSE 8081