server:
  port: 8081

spring.datasource:
  driverClassName: 'org.hibernate.dialect.PostgreSQLDialect'
  url: 'jdbc:postgresql://postgres:5432/postgres'
  username: 'postgres'
  password: 'admin1234'

spring.jpa:
  jpa.hibernate.ddl-auto: 'update'
  show-sql: true  

spring.flyway:
  baseline-on-migrate: true
  baseline-version: 0
  url: 'jdbc:postgresql://postgres:5432/postgres'
  user: 'postgres'
  password: 'admin1234'